-- Categories -----------------------------------------------------
insert into public.exercise_categories (id, catalog, name, name_en, description) values
  ('push', 'strength', 'חזה, כתפיים ויד אחורית', 'Chest, shoulders & triceps (push)', 'תרגילי דחיפה — Push movements'),
  ('back', 'strength', 'גב', 'Back (pull)', 'תרגילי משיכה — Pull movements'),
  ('lower', 'strength', 'רגליים', 'Legs', 'רגליים וישבן — Legs and glutes'),
  ('core', 'strength', 'ליבה ובטן', 'Core and abs', 'יציבות ליבה — Trunk stability and abs'),
  ('cardio', 'endurance', 'אירובי ללא ריצה', 'Cardio (no running)', 'העלאת דופק ללא ריצה — Heart-rate work without running'),
  ('dynamic_stretch', 'warmup', 'מתיחות בתנועה', 'Dynamic stretches', 'ניידות מפרקים ומתיחה תוך כדי תנועה — Mobility and stretch while moving'),
  ('pulse_raiser', 'warmup', 'העלאת דופק', 'Pulse raisers', 'תנועות קלות שמעלות דופק בהדרגה — Easy movements that gradually raise heart rate'),
  ('stretch_lower', 'cooldown', 'מתיחות פלג גוף תחתון', 'Lower body stretches', 'ירכיים, ישבן ושוקיים — Hips, glutes and calves'),
  ('stretch_upper', 'cooldown', 'מתיחות פלג גוף עליון', 'Upper body stretches', 'חזה, כתפיים וזרועות — Chest, shoulders and arms'),
  ('stretch_back', 'cooldown', 'מתיחות גב וליבה', 'Back and core stretches', 'גב תחתון, גב עליון וליבה — Lower back, upper back and core')
on conflict (id) do nothing;

-- Exercises -------------------------------------------------------
insert into public.strength_exercises (id, name, name_en, catalog, category, level, unit, units_per_rep, animation_key) values
  ('push-1-wall-pushup', 'שכיבות סמיכה בעמידה כנגד קיר', 'Wall Push-ups', 'strength', 'push', 1, 'reps', 1, 'wallpush'),
  ('push-1-knee-plank-hold', 'החזקת מצב שכיבת סמיכה על הברכיים', 'Knee Plank Hold', 'strength', 'push', 1, 'seconds', 5, 'plank'),
  ('push-1-arm-raises', 'הרמות ידיים לפנים ולצדדים ללא משקל כנגד התנגדות עצמית', 'Self-Resistance Arm Raises', 'strength', 'push', 1, 'reps', 1, 'ytw'),
  ('push-1-isometric-press', 'לחיצות ידיים איזומטריות (כף אל כף מול החזה)', 'Isometric Palm Press', 'strength', 'push', 1, 'seconds', 5, 'ytw'),
  ('push-1-wall-triceps', 'פשיטת מרפקים בעמידה כנגד קיר', 'Wall Triceps Extensions', 'strength', 'push', 1, 'reps', 1, 'wallpush'),
  ('push-2-incline-pushup', 'שכיבות סמיכה בשיפוע חיובי (ידיים על ספסל/משטח מוגבה)', 'Incline Push-ups', 'strength', 'push', 2, 'reps', 1, 'wallpush'),
  ('push-2-knee-pushup', 'שכיבות סמיכה על הברכיים', 'Knee Push-ups', 'strength', 'push', 2, 'reps', 1, 'pushup'),
  ('push-2-pike-bent-knee', 'לחיצת כתפיים בתנוחת דוב (Pike Push-ups בברכיים כפופות)', 'Bent-Knee Pike Push-ups', 'strength', 'push', 2, 'reps', 1, 'pike'),
  ('push-2-bench-dip-bent-knee', 'פשיטת מרפקים כנגד ספסל/כיסא (Bench Dips בברכיים כפופות)', 'Bent-Knee Bench Dips', 'strength', 'push', 2, 'reps', 1, 'dip'),
  ('push-2-negative-pushup', 'שכיבות סמיכה שליליות (ירידה איטית בלבד)', 'Negative Push-ups', 'strength', 'push', 2, 'reps', 1, 'pushup'),
  ('push-3-full-pushup', 'שכיבות סמיכה קלאסיות מלאות', 'Full Push-ups', 'strength', 'push', 3, 'reps', 1, 'pushup'),
  ('push-3-decline-pushup', 'שכיבות סמיכה בשיפוע שלילי (רגליים מוגבהות על ספסל)', 'Decline Push-ups', 'strength', 'push', 3, 'reps', 1, 'pushup'),
  ('push-3-pike-full', 'Pike Push-ups מלאים', 'Full Pike Push-ups', 'strength', 'push', 3, 'reps', 1, 'pike'),
  ('push-3-diamond-pushup', 'שכיבות סמיכה יהלום', 'Diamond Push-ups', 'strength', 'push', 3, 'reps', 1, 'pushup'),
  ('push-3-parallel-dip', 'Dips מלאים על מקבילים', 'Full Parallel Bar Dips', 'strength', 'push', 3, 'reps', 1, 'dip'),
  ('push-4-handstand-wall', 'שכיבות סמיכה בעמידת ידיים כנגד קיר', 'Wall Handstand Push-ups', 'strength', 'push', 4, 'reps', 1, 'pike'),
  ('push-4-clap-pushup', 'שכיבות סמיכה מתפרצות עם מחיאת כף', 'Clap Push-ups', 'strength', 'push', 4, 'reps', 1, 'pushup'),
  ('push-4-one-arm-pushup', 'שכיבות סמיכה ביד אחת', 'One-Arm Push-ups', 'strength', 'push', 4, 'reps', 1, 'pushup'),
  ('push-4-archer-pushup', 'Archer Push-ups', 'Archer Push-ups', 'strength', 'push', 4, 'reps', 1, 'pushup'),
  ('push-4-ring-dip', 'Dips בשיפוע חיובי על טבעות אולימפיות / מקבילים עם הטיה קדימה', 'Ring / Forward-Lean Dips', 'strength', 'push', 4, 'reps', 1, 'dip'),
  ('back-1-scapular-squeeze', 'קירוב שכמות בישיבה או עמידה', 'Scapular Squeezes', 'strength', 'back', 1, 'reps', 1, 'ytw'),
  ('back-1-towel-row', 'חתירה במשיכת מגבת/עמוד בעמידה בזווית קלה מאוד', 'Shallow-Angle Towel Row', 'strength', 'back', 1, 'reps', 1, 'ytw'),
  ('back-1-cobra-lift', 'שכיבה על הבטן והרמת חזה קלה בלבד (Cobra Lift ללא ניתוק רגליים)', 'Cobra Lift', 'strength', 'back', 1, 'reps', 1, 'cobra'),
  ('back-1-quadruped-balance', 'עמידת שש עם החזקת שיווי משקל (הרמת יד אחת בלבד בכל פעם)', 'Quadruped Single-Arm Balance', 'strength', 'back', 1, 'reps', 1, 'birddog'),
  ('back-1-foot-supported-hang', 'תלייה פסיבית קצרה עם רגליים על הקרקע לתמיכה', 'Foot-Supported Dead Hang', 'strength', 'back', 1, 'seconds', 5, 'plank'),
  ('back-2-inverted-row-shallow', 'חתירה אוסטרלית בעמידה/שיפוע גבוה (Inverted Rows בזווית קלה)', 'Shallow-Angle Inverted Rows', 'strength', 'back', 2, 'reps', 1, 'ytw'),
  ('back-2-superman-hold', 'סופרמן על הקרקע בהחזקה סטטית', 'Static Superman Hold', 'strength', 'back', 2, 'seconds', 5, 'cobra'),
  ('back-2-scapular-retraction', 'תרגיל Scapular Retractions בשכיבה על הבטן', 'Prone Scapular Retractions', 'strength', 'back', 2, 'reps', 1, 'cobra'),
  ('back-2-flexed-arm-hang', 'החזקת מתח סטטית בחלק העליון (Dead Hang / Flexed Arm Hang בעזרת קפיצה)', 'Flexed Arm Hang', 'strength', 'back', 2, 'seconds', 5, 'plank'),
  ('back-2-negative-pullup', 'מתח שלילי (Negative Pull-ups עם ירידה איטית)', 'Negative Pull-ups', 'strength', 'back', 2, 'reps', 1, 'ytw'),
  ('back-3-pullup', 'מתח קלאסי באחיזה עילית', 'Pull-ups', 'strength', 'back', 3, 'reps', 1, 'ytw'),
  ('back-3-chinup', 'מתח באחיזה תחתית', 'Chin-ups', 'strength', 'back', 3, 'reps', 1, 'ytw'),
  ('back-3-inverted-row', 'חתירה אוסטרלית אופקית (Inverted Rows במקביל לקרקע)', 'Horizontal Inverted Rows', 'strength', 'back', 3, 'reps', 1, 'ytw'),
  ('back-3-wide-pullup', 'מתח באחיזה רחבה', 'Wide-Grip Pull-ups', 'strength', 'back', 3, 'reps', 1, 'ytw'),
  ('back-3-superman-pulldown', 'Superman Pulldowns (משיכת מרפקים לאחור בשכיבה)', 'Superman Pulldowns', 'strength', 'back', 3, 'reps', 1, 'cobra'),
  ('back-4-muscleup', 'עליות כוח (Muscle-ups על מתח או טבעות)', 'Muscle-ups', 'strength', 'back', 4, 'reps', 1, 'ytw'),
  ('back-4-lsit-pullup', 'מתח L-Sit (Pull-ups ברגליים מורמות ב-90 מעלות)', 'L-Sit Pull-ups', 'strength', 'back', 4, 'reps', 1, 'ytw'),
  ('back-4-archer-pullup', 'Archer Pull-ups', 'Archer Pull-ups', 'strength', 'back', 4, 'reps', 1, 'ytw'),
  ('back-4-front-lever', 'Front Lever Raises / Tucks', 'Front Lever Raises / Tucks', 'strength', 'back', 4, 'reps', 1, 'legraise'),
  ('back-4-one-arm-pullup', 'מתח ביד אחת / בעזרת אצבעות בודדות', 'One-Arm / Finger Pull-ups', 'strength', 'back', 4, 'reps', 1, 'ytw'),
  ('lower-1-sit-to-stand', 'קימה וישיבה מכיסא', 'Sit-to-Stand', 'strength', 'lower', 1, 'reps', 1, 'squat'),
  ('lower-1-wall-calf-raise', 'הרמות עקבים לתאומים בעמידה עם אחיזה בקיר', 'Wall-Assisted Calf Raises', 'strength', 'lower', 1, 'reps', 1, 'calf'),
  ('lower-1-assisted-lunge-hold', 'מכרע סטטי קצר עם תמיכת ידיים על קיר/כיסא', 'Assisted Short Lunge Hold', 'strength', 'lower', 1, 'seconds', 5, 'lunge'),
  ('lower-1-hip-abduction', 'הרחקת ירך בעמידה עם אחיזה בקיר', 'Standing Hip Abductions', 'strength', 'lower', 1, 'reps', 1, 'lunge'),
  ('lower-1-short-glute-bridge', 'גשר ישבן עם טווח תנועה קצר וללא שהייה', 'Short-Range Glute Bridge', 'strength', 'lower', 1, 'reps', 1, 'bridge'),
  ('lower-2-air-squat', 'סקווט משקל גוף מלא', 'Air Squats', 'strength', 'lower', 2, 'reps', 1, 'squat'),
  ('lower-2-static-lunge', 'מכרעים במקום', 'Static Lunges', 'strength', 'lower', 2, 'reps', 1, 'lunge'),
  ('lower-2-full-glute-bridge', 'גשר ישבן מלא על שתי רגליים', 'Full Glute Bridges', 'strength', 'lower', 2, 'reps', 1, 'bridge'),
  ('lower-2-calf-raise', 'עליית עקבים לתאומים ללא אחיזה', 'Unassisted Calf Raises', 'strength', 'lower', 2, 'reps', 1, 'calf'),
  ('lower-2-wall-sit', 'ישיבה כנגד קיר', 'Wall Sit', 'strength', 'lower', 2, 'seconds', 5, 'wallsit'),
  ('lower-3-walking-lunge', 'מכרעים בהליכה', 'Walking Lunges', 'strength', 'lower', 3, 'reps', 1, 'lunge'),
  ('lower-3-bulgarian-split-squat', 'סקווט בולגרי (Bulgarian Split Squats על ספסל)', 'Bulgarian Split Squats', 'strength', 'lower', 3, 'reps', 1, 'lunge'),
  ('lower-3-single-leg-bridge', 'גשר ישבן על רגל אחת', 'Single-Leg Glute Bridge', 'strength', 'lower', 3, 'reps', 1, 'bridge'),
  ('lower-3-jump-squat', 'סקווט בקפיצה', 'Jump Squats', 'strength', 'lower', 3, 'reps', 1, 'jumpsquat'),
  ('lower-3-cossack-squat', 'מכרעים הצידה (Cossack Squats בטווח תנועה בינוני)', 'Cossack Squats', 'strength', 'lower', 3, 'reps', 1, 'lunge'),
  ('lower-4-pistol-squat', 'סקווט אקדח מלא', 'Full Pistol Squats', 'strength', 'lower', 4, 'reps', 1, 'squat'),
  ('lower-4-nordic-curl', 'Nordic Curls (לירך אחורית)', 'Nordic Curls', 'strength', 'lower', 4, 'reps', 1, 'legraise'),
  ('lower-4-jumping-split-lunge', 'מכרעים בקפיצה עם החלפת רגליים באוויר', 'Jumping Split Lunges', 'strength', 'lower', 4, 'reps', 1, 'jumpsquat'),
  ('lower-4-sissy-squat', 'סקווט סקנדינבי/ססי (Sissy Squats)', 'Sissy Squats', 'strength', 'lower', 4, 'reps', 1, 'squat'),
  ('lower-4-deep-cossack-squat', 'Cossack Squats מלאים עם שהייה עמוקה ועבודה אקסצנטרית', 'Deep Cossack Squats', 'strength', 'lower', 4, 'reps', 1, 'lunge'),
  ('core-1-wall-plank', 'פלאנק בעמידה כנגד קיר או שיפוע גבוה מאוד', 'Incline Wall Plank', 'strength', 'core', 1, 'seconds', 5, 'plank'),
  ('core-1-pelvic-tilt', 'שכיבה על הגב והצמדת הגב התחתון למזרן (Pelvic Tilts)', 'Pelvic Tilts', 'strength', 'core', 1, 'reps', 1, 'deadbug'),
  ('core-1-seated-knee-tuck', 'הרמות ברכיים בישיבה על כיסא (Seated Knee Tucks)', 'Seated Knee Tucks', 'strength', 'core', 1, 'reps', 1, 'crunch'),
  ('core-1-arms-only-deadbug', 'תרגיל Dead Bug עם רגליים על הקרקע (תנועת ידיים בלבד)', 'Arms-Only Dead Bug', 'strength', 'core', 1, 'reps', 1, 'deadbug'),
  ('core-1-quadruped-hold', 'עמידת שש עם שמירה על מנח ניטרלי (Quadruped Hold)', 'Quadruped Neutral Hold', 'strength', 'core', 1, 'seconds', 5, 'birddog'),
  ('core-2-forearm-plank', 'פלאנק סטטי על האמות', 'Forearm Plank', 'strength', 'core', 2, 'seconds', 5, 'plank'),
  ('core-2-side-plank-knee', 'פלאנק צידי על הברכיים', 'Side Plank on Knees', 'strength', 'core', 2, 'seconds', 5, 'sideplank'),
  ('core-2-crunch', 'כפיפות בטן קלאסיות', 'Crunches', 'strength', 'core', 2, 'reps', 1, 'crunch'),
  ('core-2-deadbug-full', 'תרגיל Dead Bug מלא', 'Full Dead Bug', 'strength', 'core', 2, 'reps', 1, 'deadbug'),
  ('core-2-birddog', 'תרגיל Bird-Dog', 'Bird-Dog', 'strength', 'core', 2, 'reps', 1, 'birddog'),
  ('core-3-side-plank-leg-raise', 'פלאנק צידי מלא עם הרמת רגל עליונה', 'Side Plank with Leg Raise', 'strength', 'core', 3, 'seconds', 5, 'sideplank'),
  ('core-3-hanging-knee-raise', 'הרמות ברכיים בתלייה על מתח (Hanging Knee Raises)', 'Hanging Knee Raises', 'strength', 'core', 3, 'reps', 1, 'legraise'),
  ('core-3-bicycle-crunch', 'אופניים (Bicycle Crunches)', 'Bicycle Crunches', 'strength', 'core', 3, 'reps', 1, 'twist'),
  ('core-3-reverse-crunch', 'גלגול אגן לאחור (Reverse Crunches)', 'Reverse Crunches', 'strength', 'core', 3, 'reps', 1, 'crunch'),
  ('core-3-mountain-climber', 'Mountain Climbers בקצב מבוקר', 'Controlled Mountain Climbers', 'strength', 'core', 3, 'reps', 1, 'climber'),
  ('core-4-toes-to-bar', 'הרמות רגליים ישרות למתח (Toes to Bar)', 'Toes to Bar', 'strength', 'core', 4, 'reps', 1, 'legraise'),
  ('core-4-dragon-flag', 'Dragon Flags', 'Dragon Flags', 'strength', 'core', 4, 'reps', 1, 'crunch'),
  ('core-4-lsit', 'L-Sit מלא על מקבילים או קרקע', 'Full L-Sit', 'strength', 'core', 4, 'seconds', 5, 'legraise'),
  ('core-4-ab-wheel', 'פלאנק עם גלגלת בטן / פלאנק ארוך', 'Ab Wheel / Extended Plank', 'strength', 'core', 4, 'seconds', 5, 'plank'),
  ('core-4-vup', 'V-Ups מלאים', 'Full V-Ups', 'strength', 'core', 4, 'reps', 1, 'crunch'),
  ('cardio-1-marching', 'צעידה מתונה במקום', 'Moderate Marching in Place', 'endurance', 'cardio', 1, 'seconds', 5, 'highknee'),
  ('cardio-1-step-touch', 'Step-Touch (צעד הצידה ונגיעה) ללא קפיצות', 'Step-Touch (No Hop)', 'endurance', 'cardio', 1, 'seconds', 5, 'stepup'),
  ('cardio-1-slow-knee-raise', 'הרמת ברך לגובה האגן לסירוגין בקצב איטי', 'Slow Alternating Knee Raise', 'endurance', 'cardio', 1, 'seconds', 5, 'highknee'),
  ('cardio-1-step-jacks', 'פתיחת ידיים ורגליים לסירוגין ללא ניתור (Step-Jacks)', 'Step-Jacks', 'endurance', 'cardio', 1, 'seconds', 5, 'jumpingjack'),
  ('cardio-1-slow-shadow-box', 'איגרוף איטי באוויר בעמידה יציבה', 'Slow Shadow Boxing', 'endurance', 'cardio', 1, 'seconds', 5, 'ytw'),
  ('cardio-2-jumping-jacks', 'Jumping Jacks בקצב אחיד', 'Steady-Pace Jumping Jacks', 'endurance', 'cardio', 2, 'seconds', 5, 'jumpingjack'),
  ('cardio-2-skaters-no-hop', 'צעדי החלקה מצד לצד (Skaters ללא ניתור)', 'Skaters (No Hop)', 'endurance', 'cardio', 2, 'seconds', 5, 'skater'),
  ('cardio-2-low-stepups', 'Step-ups על מדרגה נמוכה', 'Low Step-ups', 'endurance', 'cardio', 2, 'seconds', 5, 'stepup'),
  ('cardio-2-shadow-box', 'צל-איגרוף (Shadow Boxing) בקצב מתון', 'Shadow Boxing (Moderate)', 'endurance', 'cardio', 2, 'seconds', 5, 'ytw'),
  ('cardio-2-standing-knee-raise', 'הרמות ברכיים לסירוגין בעמידה', 'Alternating Standing Knee Raises', 'endurance', 'cardio', 2, 'seconds', 5, 'highknee'),
  ('cardio-3-rope-single', 'קפיצה על חבל (Single Unders)', 'Jump Rope — Single Unders', 'endurance', 'cardio', 3, 'seconds', 5, 'rope'),
  ('cardio-3-fast-mountain-climber', 'Mountain Climbers מהירים', 'Fast Mountain Climbers', 'endurance', 'cardio', 3, 'seconds', 5, 'climber'),
  ('cardio-3-wide-skaters', 'Skaters עם ניתור רחב', 'Wide-Hop Skaters', 'endurance', 'cardio', 3, 'seconds', 5, 'skater'),
  ('cardio-3-sprawls', 'Burpees ללא שכיבת סמיכה (Sprawls)', 'Sprawls', 'endurance', 'cardio', 3, 'seconds', 5, 'burpee'),
  ('cardio-3-high-knees', 'High Knees במקום', 'High Knees in Place', 'endurance', 'cardio', 3, 'seconds', 5, 'highknee'),
  ('cardio-4-burpees', 'Burpees מלאים (שכיבת סמיכה וניתור לגובה)', 'Full Burpees', 'endurance', 'cardio', 4, 'seconds', 5, 'burpee'),
  ('cardio-4-rope-double', 'קפיצה על חבל בקפיצות כפולות (Double Unders)', 'Jump Rope — Double Unders', 'endurance', 'cardio', 4, 'seconds', 5, 'rope'),
  ('cardio-4-tuck-jumps', 'Tuck Jumps (קפיצות ברכיים לחזה)', 'Tuck Jumps', 'endurance', 'cardio', 4, 'seconds', 5, 'jumpsquat'),
  ('cardio-4-squat-thrusts', 'Squat Thrusts מתפרצים', 'Explosive Squat Thrusts', 'endurance', 'cardio', 4, 'seconds', 5, 'burpee'),
  ('cardio-4-bear-crawl-fast', 'Bear Crawl מהיר קדימה-אחורה', 'Fast Bear Crawl', 'endurance', 'cardio', 4, 'meters', 2, 'crawl'),
  ('warm-dyn-1-leg-swing', 'נדנוד רגליים קדימה ואחורה', 'Leg Swings', 'warmup', 'dynamic_stretch', 1, 'reps', 1, 'lunge'),
  ('warm-dyn-1-arm-circle', 'סיבובי זרועות', 'Arm Circles', 'warmup', 'dynamic_stretch', 1, 'reps', 1, 'ytw'),
  ('warm-dyn-1-torso-twist', 'סיבובי גו קלים', 'Torso Twists', 'warmup', 'dynamic_stretch', 1, 'reps', 1, 'twist'),
  ('warm-dyn-2-walking-lunge', 'לאנג׳ הליכה עם סיבוב', 'Walking Lunge with Twist', 'warmup', 'dynamic_stretch', 2, 'reps', 1, 'lunge'),
  ('warm-dyn-2-hip-circle', 'סיבובי ירך בעמידה', 'Hip Circles', 'warmup', 'dynamic_stretch', 2, 'reps', 1, 'twist'),
  ('warm-dyn-2-cat-cow', 'חתול-פרה בעמידה על ארבע', 'Cat-Cow', 'warmup', 'dynamic_stretch', 2, 'reps', 1, 'cobra'),
  ('warm-dyn-3-inchworm', 'אינצ׳וורם עד פלאנק', 'Inchworm to Plank', 'warmup', 'dynamic_stretch', 3, 'reps', 1, 'plank'),
  ('warm-dyn-3-world-greatest', 'המתיחה הטובה בעולם', 'World''s Greatest Stretch', 'warmup', 'dynamic_stretch', 3, 'reps', 1, 'lunge'),
  ('warm-pulse-1-march', 'צעידה קלה במקום', 'Easy Marching', 'warmup', 'pulse_raiser', 1, 'reps', 1, 'highknee'),
  ('warm-pulse-1-arm-swing', 'נפנוף ידיים בהליכה קלה', 'Arm Swings while Marching', 'warmup', 'pulse_raiser', 1, 'reps', 1, 'ytw'),
  ('warm-pulse-2-jumping-jack', 'ג׳אמפינג ג׳ק קל', 'Easy Jumping Jacks', 'warmup', 'pulse_raiser', 2, 'reps', 1, 'jumpingjack'),
  ('warm-pulse-2-high-knees', 'ברכיים גבוהות בקצב בינוני', 'High Knees', 'warmup', 'pulse_raiser', 2, 'reps', 1, 'highknee'),
  ('warm-pulse-3-skater', 'קפיצות סקייטר קלות', 'Light Skater Hops', 'warmup', 'pulse_raiser', 3, 'reps', 1, 'skater'),
  ('cool-low-1-quad', 'מתיחת ירך קדמית בעמידה', 'Standing Quad Stretch', 'cooldown', 'stretch_lower', 1, 'seconds', 5, 'wallsit'),
  ('cool-low-1-calf', 'מתיחת תאומים על קיר', 'Wall Calf Stretch', 'cooldown', 'stretch_lower', 1, 'seconds', 5, 'wallsit'),
  ('cool-low-2-hamstring', 'מתיחת ירך אחורית בישיבה', 'Seated Hamstring Stretch', 'cooldown', 'stretch_lower', 2, 'seconds', 5, 'plank'),
  ('cool-low-2-hip-flexor', 'מתיחת מפשעה בלאנג׳', 'Kneeling Hip Flexor Stretch', 'cooldown', 'stretch_lower', 2, 'seconds', 5, 'lunge'),
  ('cool-low-3-pigeon', 'תנוחת יונה למתיחת ישבן', 'Pigeon Pose', 'cooldown', 'stretch_lower', 3, 'seconds', 5, 'sideplank'),
  ('cool-up-1-shoulder', 'מתיחת כתף חוצה גוף', 'Cross-body Shoulder Stretch', 'cooldown', 'stretch_upper', 1, 'seconds', 5, 'ytw'),
  ('cool-up-1-triceps', 'מתיחת יד אחורית מעל הראש', 'Overhead Triceps Stretch', 'cooldown', 'stretch_upper', 1, 'seconds', 5, 'ytw'),
  ('cool-up-2-chest', 'מתיחת חזה בפתח דלת', 'Doorway Chest Stretch', 'cooldown', 'stretch_upper', 2, 'seconds', 5, 'cobra'),
  ('cool-up-2-wrist', 'מתיחת אמות ופרקי כף יד', 'Wrist and Forearm Stretch', 'cooldown', 'stretch_upper', 2, 'seconds', 5, 'ytw'),
  ('cool-back-1-child', 'תנוחת הילד', 'Child''s Pose', 'cooldown', 'stretch_back', 1, 'seconds', 5, 'cobra'),
  ('cool-back-1-cat', 'חתול-פרה סטטי', 'Static Cat-Cow', 'cooldown', 'stretch_back', 1, 'seconds', 5, 'cobra'),
  ('cool-back-2-knee-hug', 'חיבוק ברכיים לחזה', 'Knee-to-Chest Hug', 'cooldown', 'stretch_back', 2, 'seconds', 5, 'deadbug'),
  ('cool-back-3-spinal-twist', 'פיתול גב שכיבה', 'Supine Spinal Twist', 'cooldown', 'stretch_back', 3, 'seconds', 5, 'twist')
on conflict (id) do nothing;
