/**
 * Cool-down catalogue — static stretches held after a training. Same points
 * mechanics as the rest of the app (points = reps x level; held stretches
 * score every 5 seconds as a rep), so cool-down rounds reuse the same
 * interval/points screen as everything else.
 */
import { withRealGif } from './strength-catalog';
import type {
  AnimationKey,
  CooldownCategoryId,
  StrengthCategory,
  StrengthExercise,
  StrengthLevel,
  StrengthUnit,
} from './strength-catalog';

export const COOLDOWN_CATEGORIES: StrengthCategory[] = [
  {
    id: 'stretch_lower',
    name: 'מתיחות פלג גוף תחתון',
    nameEn: 'Lower body stretches',
    description: 'ירכיים, ישבן ושוקיים — Hips, glutes and calves',
  },
  {
    id: 'stretch_upper',
    name: 'מתיחות פלג גוף עליון',
    nameEn: 'Upper body stretches',
    description: 'חזה, כתפיים וזרועות — Chest, shoulders and arms',
  },
  {
    id: 'stretch_back',
    name: 'מתיחות גב וליבה',
    nameEn: 'Back and core stretches',
    description: 'גב תחתון, גב עליון וליבה — Lower back, upper back and core',
  },
];

const e = (
  id: string,
  name: string,
  nameEn: string,
  category: CooldownCategoryId,
  level: StrengthLevel,
  animation: AnimationKey,
  instructions: string,
  unit: StrengthUnit = 'seconds',
  unitsPerRep?: number,
): StrengthExercise => ({
  id,
  name,
  nameEn,
  catalog: 'cooldown',
  category,
  level,
  unit,
  unitsPerRep: unitsPerRep ?? (unit === 'seconds' ? 5 : unit === 'meters' ? 2 : 1),
  animation,
  instructions,
  gif_url: null,
});

export const COOLDOWN_EXERCISES: StrengthExercise[] = [
  /* ------------------------------------- מתיחות פלג גוף תחתון */
  e(
    'cool-low-1-quad',
    'מתיחת ירך קדמית בעמידה',
    'Standing Quad Stretch',
    'stretch_lower',
    1,
    'wallsit',
    'עמדו על רגל אחת, אחזו בקרסול הרגל השנייה ומשכו אותה לאחור לעבר הישבן תוך שמירה על ברכיים צמודות.',
  ),
  e(
    'cool-low-1-calf',
    'מתיחת תאומים על קיר',
    'Wall Calf Stretch',
    'stretch_lower',
    1,
    'wallsit',
    'הישענו בידיים על קיר, הניחו רגל אחת מאחור עם עקב שטוח על הרצפה ורגל קדמית כפופה, עד תחושת מתיחה בשוק האחורית.',
  ),
  e(
    'cool-low-2-hamstring',
    'מתיחת ירך אחורית בישיבה',
    'Seated Hamstring Stretch',
    'stretch_lower',
    2,
    'plank',
    'שבו עם רגל אחת ישרה קדימה והשנייה כפופה. התכופפו לאט לעבר כף הרגל הישרה עד מתיחה נעימה בירך האחורית.',
  ),
  e(
    'cool-low-2-hip-flexor',
    'מתיחת מפשעה בלאנג׳',
    'Kneeling Hip Flexor Stretch',
    'stretch_lower',
    2,
    'lunge',
    'הניחו ברך אחת על הרצפה ורגל שנייה כפופה לפנים. דחפו את האגן קדימה בעדינות למתיחת המפשעה של הרגל האחורית.',
  ),
  e(
    'cool-low-3-pigeon',
    'תנוחת יונה למתיחת ישבן',
    'Pigeon Pose',
    'stretch_lower',
    3,
    'sideplank',
    'הביאו רגל אחת כפופה לפנים ורגל שנייה ישרה מאחור, ושקעו את האגן לרצפה למתיחה עמוקה של הישבן.',
  ),
  e(
    'cool-low-2-seated-glute-stretch',
    'מתיחת ישבן בישיבה',
    'Seated Glute Stretch',
    'stretch_lower',
    2,
    'plank',
    'שבו על הרצפה וקרבו רגל אחת מקופלת לכיוון החזה בעדינות למתיחת שריר הישבן.',
  ),
  e(
    'cool-low-2-piriformis-stretch',
    'מתיחת פיריפורמיס בישיבה',
    'Seated Piriformis Stretch',
    'stretch_lower',
    2,
    'plank',
    'שבו והניחו את הקרסול על הברך הנגדית, והתכופפו קדימה למתיחת שריר הפיריפורמיס.',
  ),
  e(
    'cool-low-2-side-quad-stretch',
    'מתיחת ירך קדמית בשכיבה על הצד',
    'Lying Side Quads Stretch',
    'stretch_lower',
    2,
    'sideplank',
    'שכבו על הצד ואחזו בקרסול הרגל העליונה, ומשכו אותה לאחור בעדינות למתיחת הירך הקדמית.',
  ),

  /* -------------------------------------- מתיחות פלג גוף עליון */
  e(
    'cool-up-1-shoulder',
    'מתיחת כתף חוצה גוף',
    'Cross-body Shoulder Stretch',
    'stretch_upper',
    1,
    'ytw',
    'העבירו זרוע אחת לרוחב החזה ואחזו אותה בעדינות עם היד השנייה עד מתיחה בכתף האחורית.',
  ),
  e(
    'cool-up-1-triceps',
    'מתיחת יד אחורית מעל הראש',
    'Overhead Triceps Stretch',
    'stretch_upper',
    1,
    'ytw',
    'הרימו זרוע אחת מעל הראש, כופפו את המרפק ולחצו בעדינות עם היד השנייה למתיחת התלת ראשי.',
  ),
  e(
    'cool-up-2-chest',
    'מתיחת חזה בפתח דלת',
    'Doorway Chest Stretch',
    'stretch_upper',
    2,
    'cobra',
    'הניחו אמה על משקוף הדלת בזווית 90 מעלות והטו את הגוף קדימה בעדינות למתיחת החזה.',
  ),
  e(
    'cool-up-2-wrist',
    'מתיחת אמות ופרקי כף יד',
    'Wrist and Forearm Stretch',
    'stretch_upper',
    2,
    'ytw',
    'הושיטו זרוע קדימה עם כף היד פונה למעלה ומשכו את האצבעות לאחור בעדינות עם היד השנייה.',
  ),
  e(
    'cool-up-1-back-pec-stretch',
    'מתיחת חזה מהגב',
    'Back Pec Stretch',
    'stretch_upper',
    1,
    'ytw',
    'שלבו ידיים מאחורי הגב והרימו אותן מעט כלפי מעלה למתיחת שרירי החזה והכתפיים הקדמיות.',
  ),
  e(
    'cool-up-2-rear-deltoid-stretch',
    'מתיחת כתף אחורית',
    'Rear Deltoid Stretch',
    'stretch_upper',
    2,
    'ytw',
    'העבירו זרוע אחת לרוחב הגוף בגובה החזה ודחפו אותה בעדינות עם היד השנייה למתיחת הכתף האחורית.',
  ),
  e(
    'cool-up-2-triceps-stretch',
    'מתיחת תלת ראשי',
    'Triceps Stretch',
    'stretch_upper',
    2,
    'ytw',
    'החזיקו יד אחת כפופה מאחורי הראש והפעילו לחץ עדין עם היד השנייה למתיחה מלאה של התלת ראשי.',
  ),
  e(
    'cool-up-3-iron-cross-stretch',
    'מתיחת צלב חזה',
    'Iron Cross Stretch',
    'stretch_upper',
    3,
    'cobra',
    'שכבו על הבטן עם ידיים פרושות לצדדים בצורת צלב, ותנו למשקל הגוף לפתוח בעדינות את החזה והכתפיים.',
  ),

  /* ---------------------------------------- מתיחות גב וליבה */
  e(
    'cool-back-1-child',
    'תנוחת הילד',
    "Child's Pose",
    'stretch_back',
    1,
    'cobra',
    'שבו על העקבים והטו את פלג הגוף קדימה עם ידיים מושטות, עד מתיחה נעימה בגב התחתון.',
  ),
  e(
    'cool-back-1-cat',
    'חתול-פרה סטטי',
    'Static Cat-Cow',
    'stretch_back',
    1,
    'cobra',
    'על ארבע, עגלו את הגב כלפי מעלה והחזיקו כמה שניות, ואז שקעו לעמדת פרה עם גב שקוע.',
  ),
  e(
    'cool-back-2-knee-hug',
    'חיבוק ברכיים לחזה',
    'Knee-to-Chest Hug',
    'stretch_back',
    2,
    'deadbug',
    'שכבו על הגב וחבקו את שתי הברכיים אל החזה, עד מתיחה נעימה בגב התחתון.',
  ),
  e(
    'cool-back-3-spinal-twist',
    'פיתול גב שכיבה',
    'Supine Spinal Twist',
    'stretch_back',
    3,
    'twist',
    'שכבו על הגב והפילו את הברכיים הכפופות לצד אחד תוך שמירה על כתפיים על הרצפה.',
  ),
  e(
    'cool-back-1-kneeling-lat-stretch',
    'מתיחת גב רחב בכריעה',
    'Kneeling Lat Stretch',
    'stretch_back',
    1,
    'cobra',
    'הישארו בכריעה ושילחו את הידיים קדימה והצידה על הרצפה למתיחה עמוקה של הגב הרחב.',
  ),
  e(
    'cool-back-1-seated-lower-back-stretch',
    'מתיחת גב תחתון בישיבה',
    'Seated Lower Back Stretch',
    'stretch_back',
    1,
    'plank',
    'שבו על הרצפה והתכופפו קדימה בשחרור מלא לעבר כפות הרגליים.',
  ),
  e(
    'cool-back-2-upper-back-stretch',
    'מתיחת גב עליון',
    'Upper Back Stretch',
    'stretch_back',
    2,
    'ytw',
    'שלבו ידיים קדימה בגובה החזה ודחפו את הגב החוצה תוך עיגול הכתפיים קדימה.',
  ),
  e(
    'cool-back-1-sphinx',
    'תנוחת ספינקס',
    'Sphinx',
    'stretch_back',
    1,
    'cobra',
    'שכבו על הבטן והישענו על האמות תוך הרמת החזה בעדינות, לפתיחת בית החזה והגב התחתון.',
  ),
  e(
    'cool-back-2-upward-dog',
    'תנוחת כלב פונה למעלה',
    'Upward Facing Dog',
    'stretch_back',
    2,
    'cobra',
    'משכיבה על הבטן, יישרו את הזרועות והרימו את החזה והאגן מהרצפה למתיחת קדמת הגוף.',
  ),
  e(
    'cool-back-2-spine-stretch',
    'מתיחת עמוד שדרה בישיבה',
    'Spine Stretch',
    'stretch_back',
    2,
    'plank',
    'שבו עם רגליים ישרות ורכנו קדימה באיטיות למתיחת עמוד השדרה ושרירי הגב.',
  ),
  e(
    'cool-back-2-bent-knee-twist',
    'פיתול ברכיים כפופות',
    'Bent Knee Lying Twist',
    'stretch_back',
    2,
    'twist',
    'שכבו על הגב עם ברכיים כפופות והפילו אותן יחד לצד אחד, כתפיים נשארות על הרצפה.',
  ),
  e(
    'cool-back-2-spine-twist-seated',
    'פיתול עמוד שדרה',
    'Spine Twist',
    'stretch_back',
    2,
    'twist',
    'שבו או שכבו ובצעו פיתול מבוקר ואיטי של עמוד השדרה לצד אחד ואז לצד השני.',
  ),
  e(
    'cool-back-1-pelvic-tilt',
    'הטיית אגן בעמידה',
    'Standing Pelvic Tilt',
    'stretch_back',
    1,
    'bridge',
    'עמדו והטו את האגן קדימה ואחורה בתנועה עדינה ואיטית לשחרור הגב התחתון.',
  ),
  e(
    'cool-back-1-butterfly-pose',
    'תנוחת פרפר',
    'Butterfly Yoga Pose',
    'stretch_back',
    1,
    'plank',
    'שבו עם כפות רגליים צמודות זו לזו וברכיים פתוחות לצדדים, ונשמו עמוק תוך הרפיה.',
  ),

  /* -------------------------------------- מתיחות צוואר (no dedicated catalogue yet — filed under upper body) */
  e(
    'cool-up-3-neck-front-back',
    'מתיחת צוואר קדימה ואחורה',
    'Front and Back Neck Stretch',
    'stretch_upper',
    1,
    'ytw',
    'הטו את הראש בעדינות קדימה עד מתיחה בעורף, ולאחר מכן אחורה בזהירות רבה.',
  ),
  e(
    'cool-up-3-neck-side',
    'מתיחת צוואר לצדדים',
    'Side Neck Stretch',
    'stretch_upper',
    1,
    'ytw',
    'הטו את הראש לצד אחד לעבר הכתף עד מתיחה עדינה בצוואר, וחזרו למרכז לפני החלפת צד.',
  ),
  e(
    'cool-up-3-neck-rotation',
    'סיבוב צוואר איטי',
    'Slow Neck Rotation',
    'stretch_upper',
    2,
    'ytw',
    'סובבו את הראש לאט ובזהירות במעגל מלא, בכיוון אחד ולאחר מכן בכיוון הנגדי.',
  ),
].map(withRealGif);
