import { withRealGif } from './strength-catalog';
import type {
  AnimationKey,
  EnduranceCategoryId,
  StrengthCategory,
  StrengthExercise,
  StrengthLevel,
  StrengthUnit,
} from './strength-catalog';

export const ENDURANCE_CATEGORIES: StrengthCategory[] = [
  {
    id: 'cardio',
    name: 'אירובי',
    nameEn: 'Cardio',
    description: 'העלאת דופק — Heart-rate work',
  },
];

const e = (
  id: string,
  name: string,
  nameEn: string,
  category: EnduranceCategoryId,
  level: StrengthLevel,
  animation: AnimationKey,
  instructions: string,
  unit: StrengthUnit = 'seconds',
): StrengthExercise => ({
  id,
  name,
  nameEn,
  catalog: 'endurance',
  category,
  level,
  unit,
  unitsPerRep: unit === 'seconds' ? 5 : unit === 'meters' ? 2 : 1,
  animation,
  instructions,
  gif_url: null,
});

export const ENDURANCE_EXERCISES: StrengthExercise[] = [
  /* ============================================= רמה 1 — מתחיל ============================================= */
  e(
    'cardio-1-jumping-jacks',
    'קפיצות פישוק',
    'Jumping Jacks',
    'cardio',
    1,
    'jumpingjack',
    'עמדו רגליים צמודות. קפצו תוך פשיקת רגליים והנפת ידיים מעל הראש, וקפצו חזרה למצב הפתיחה.',
  ),
  e(
    'cardio-1-quick-steps',
    'צעדים מהירים במקום',
    'Quick Steps',
    'cardio',
    1,
    'stepup',
    'עמדו במקום וצעדו קדימה ואחורה במהירות, רגל אחר רגל, תוך הנעת הידיים בטבעיות.',
  ),
  e(
    'cardio-1-fast-half-squats',
    'חצאי סקוואט מהירים',
    'Fast Half Squats',
    'cardio',
    1,
    'squat',
    'עמדו ברוחב הכתפיים ובצעו כיפוף ברכיים רדוד וקצבי, בלי לרדת לסקוואט מלא.',
  ),
  e(
    'cardio-1-wall-high-knees',
    'הרמות ברכיים מול קיר',
    'Wall High Knees',
    'cardio',
    1,
    'highknee',
    'הישענו בידיים על קיר ורוצו במקום תוך הרמת ברכיים לכיוון החזה בקצב מהיר.',
  ),
  e(
    'cardio-1-seal-jacks',
    'פישוק ידיים',
    'Seal Jacks',
    'cardio',
    1,
    'jumpingjack',
    'כמו קפיצות פישוק, אך במקום להניף ידיים למעלה פתחו וסגרו זרועות ישרות קדימה בגובה החזה.',
  ),
  e(
    'cardio-1-running-in-place',
    'ריצה במקום',
    'Running in Place',
    'cardio',
    1,
    'highknee',
    'רוצו במקום תוך הנעת הידיים כרגיל, בקצב אחיד ובנשימה סדירה.',
  ),
  e(
    'cardio-1-fast-feet',
    'רגליים מהירות',
    'Fast Feet',
    'cardio',
    1,
    'highknee',
    'ברכיים מעט כפופות, הרימו והורידו את כפות הרגליים במהירות בצעדים קטנים.',
  ),

  /* ============================================= רמה 2 — בינוני ============================================= */
  e(
    'cardio-2-backward-broad-jump',
    'קפיצת רוחק לאחור',
    'Backward Broad Jump',
    'cardio',
    2,
    'jumpsquat',
    'כופפו ברכיים וקפצו לאחור למרחק המרבי, ונחתו רך על שתי הרגליים.',
  ),
  e(
    'cardio-2-bear-crawl',
    'זחילת דוב',
    'Bear Crawl',
    'cardio',
    2,
    'crawl',
    'עמידת שש עם ברכיים מעט מעל הרצפה. זחלו קדימה על ידי הזזת יד ורגל נגדיות יחד.',
    'meters',
  ),
  e(
    'cardio-2-drop-squat',
    'נפילה לסקוואט',
    'Drop Squat',
    'cardio',
    2,
    'jumpsquat',
    'מעמידה צרה, קפצו ופשקו רגליים תוך ירידה מהירה לסקוואט ונגיעה ברצפה ביד.',
  ),
  e(
    'cardio-2-cross-body-mountain-climber',
    'טיפוס הרים אלכסוני',
    'Cross Body Mountain Climber',
    'cardio',
    2,
    'climber',
    'מתנוחת פלאנק, הביאו ברך אל המרפק הנגדי לסירוגין במהירות.',
  ),
  e(
    'cardio-2-forward-broad-jump',
    'קפיצת רוחק קדימה',
    'Forward Broad Jump',
    'cardio',
    2,
    'jumpsquat',
    'כופפו ברכיים וקפצו קדימה למרחק המרבי, נחתו רך ועברו מיד לקפיצה הבאה.',
  ),
  e(
    'cardio-2-jump-squat',
    'סקוואט בקפיצה',
    'Jump Squat',
    'cardio',
    2,
    'jumpsquat',
    'רדו לסקוואט וקפצו למעלה בפיצוץ כוח, ונחתו רך בחזרה לסקוואט הבא.',
  ),
  e(
    'cardio-2-mountain-climber',
    'טיפוס הרים',
    'Mountain Climber',
    'cardio',
    2,
    'climber',
    'מתנוחת פלאנק, הביאו ברכיים לחזה לסירוגין במהירות כמו ריצה.',
  ),
  e(
    'cardio-2-sprinter-start',
    'זינוק אצן',
    'Sprinter Start',
    'cardio',
    2,
    'highknee',
    'תנוחת זינוק עם רגל אחת קדימה וידיים על הרצפה. החליפו רגליים במהירות מבלי להתרומם.',
  ),
  e(
    'cardio-2-scissor-jumps',
    'קפיצות מספריים',
    'Scissor Jumps',
    'cardio',
    2,
    'jumpsquat',
    'קפצו והחליפו רגל קדימה ואחורה לסירוגין, תוך הנעת הידיים בהתאמה.',
  ),
  e(
    'cardio-2-half-squat-jump',
    'קפיצה מחצי סקוואט',
    'Half Squat Jump',
    'cardio',
    2,
    'jumpsquat',
    'רדו לחצי סקוואט וקפצו מיד למעלה, וחזרו על כך בלי לרדת לסקוואט מלא.',
  ),
  e(
    'cardio-2-skater-hops',
    'קפיצות סקייטר',
    'Skater Hops',
    'cardio',
    2,
    'skater',
    'קפצו מצד לצד מרגל לרגל, כאשר הרגל השנייה חולפת מאחורי הגוף בכל נחיתה.',
  ),
  e(
    'cardio-2-ski-jumps',
    'קפיצות סקי',
    'Ski Jumps',
    'cardio',
    2,
    'jumpsquat',
    'רגליים צמודות, קפצו מצד לצד מעל קו דמיוני בקצב מהיר.',
  ),
  e(
    'cardio-2-high-knee-walking-lunge',
    'מכרעים בהליכה עם ברך גבוהה',
    'High Knee Walking Lunge',
    'cardio',
    2,
    'lunge',
    'בצעו מכרע קדימה, ובעלייה הניפו את הברך האחורית גבוה לכיוון החזה לפני הצעד הבא.',
  ),
  e(
    'cardio-2-high-knees-run',
    'ריצה עם ברכיים גבוהות',
    'High Knees Run',
    'cardio',
    2,
    'highknee',
    'רוצו במקום תוך הרמת הברכיים הכי גבוה שאפשר, בקצב מהיר ומתפרץ.',
  ),
  e(
    'cardio-2-speed-cross-body-crunch',
    'כפיפות בטן אלכסוניות מהירות',
    'Speed Cross Body Crunch',
    'cardio',
    2,
    'twist',
    'שכבו על הגב ובצעו כפיפות בטן אלכסוניות (מרפק לברך נגדית) בקצב מהיר ורציף.',
  ),

  /* ============================================= רמה 3 — מתקדם ============================================= */
  e(
    'cardio-3-burpee',
    'ברפי מלא',
    'Burpee',
    'cardio',
    3,
    'burpee',
    'רדו לסקוואט ולשכיבת סמיכה, קפצו רגליים לאחור ואז חזרה פנימה, וקפצו למעלה עם ידיים באוויר.',
  ),
  e(
    'cardio-3-jack-burpee',
    'ברפי עם פישוק',
    'Jack Burpee',
    'cardio',
    3,
    'burpee',
    'בצעו ברפי רגיל, אך בתנוחת הפלאנק הוסיפו קפיצת פישוק ברגליים לפני החזרה לעמידה.',
  ),
  e(
    'cardio-3-tuck-jump',
    'קפיצת קיפול ברכיים',
    'Tuck Jump',
    'cardio',
    3,
    'jumpsquat',
    'קפצו ישר למעלה ומשכו את הברכיים גבוה לכיוון החזה באוויר, ונחתו רך.',
  ),
  e(
    'cardio-3-jumping-lunges',
    'מכרעים בקפיצה',
    'Jumping Lunges',
    'cardio',
    3,
    'jumpsquat',
    'מתוך מכרע, קפצו למעלה והחליפו רגליים באוויר לנחיתה במכרע הפוך.',
  ),
  e(
    'cardio-3-star-jump',
    'קפיצת כוכב',
    'Star Jump',
    'cardio',
    3,
    'jumpingjack',
    'מחצי סקוואט צר, קפצו למעלה ופשקו ידיים ורגליים ביצירת צורת כוכב באוויר.',
  ),
  e(
    'cardio-3-360-jump',
    'קפיצת סיבוב 360',
    '360 Jump',
    'cardio',
    3,
    'jumpsquat',
    'קפצו למעלה תוך סיבוב מלא של הגוף (360 מעלות) ונחתו בשליטה.',
  ),
  e(
    'cardio-3-plyometric-pushup',
    'שכיבת סמיכה מתפרצת',
    'Plyometric Push-Up',
    'cardio',
    3,
    'pushup',
    'בצעו שכיבת סמיכה, ובעלייה דחפו חזק כדי שהידיים יתנתקו מהרצפה לרגע.',
  ),
  e(
    'cardio-3-cardio-vup',
    'V-Up מהיר',
    'Cardio V-Up',
    'cardio',
    3,
    'crunch',
    'משכיבה על הגב, עלו במהירות ל-V-Up (ידיים ורגליים נפגשות למעלה) וחזרו מיד לרצפה.',
  ),
].map(withRealGif);
