/**
 * Warm-up catalogue — dynamic stretching and pulse-raising movements meant to
 * open a training safely. Same points mechanics as the other catalogues
 * (points = reps x level), used mainly so warm-up rounds fit the same
 * interval/points screen as everything else.
 */
import { withRealGif } from './strength-catalog';
import type {
  AnimationKey,
  StrengthCategory,
  StrengthExercise,
  StrengthLevel,
  StrengthUnit,
  WarmupCategoryId,
} from './strength-catalog';

export const WARMUP_CATEGORIES: StrengthCategory[] = [
  {
    id: 'dynamic_stretch',
    name: 'מתיחות בתנועה',
    nameEn: 'Dynamic stretches',
    description: 'ניידות מפרקים ומתיחה תוך כדי תנועה — Mobility and stretch while moving',
  },
  {
    id: 'pulse_raiser',
    name: 'העלאת דופק',
    nameEn: 'Pulse raisers',
    description: 'תנועות קלות שמעלות דופק בהדרגה — Easy movements that gradually raise heart rate',
  },
];

const e = (
  id: string,
  name: string,
  nameEn: string,
  category: WarmupCategoryId,
  level: StrengthLevel,
  animation: AnimationKey,
  instructions: string,
  unit: StrengthUnit = 'reps',
  unitsPerRep?: number,
): StrengthExercise => ({
  id,
  name,
  nameEn,
  catalog: 'warmup',
  category,
  level,
  unit,
  unitsPerRep: unitsPerRep ?? (unit === 'seconds' ? 5 : unit === 'meters' ? 2 : 1),
  animation,
  instructions,
  gif_url: null,
});

export const WARMUP_EXERCISES: StrengthExercise[] = [
  /* ------------------------------------------- מתיחות בתנועה */
  e(
    'warm-dyn-1-leg-swing',
    'נדנוד רגליים קדימה ואחורה',
    'Leg Swings',
    'dynamic_stretch',
    1,
    'lunge',
    'התייצבו ליד קיר או כיסא לתמיכה, ונדנדו רגל אחת קדימה ואחורה בתנועה חופשית ורחבה. בצעו מספר חזרות והחליפו רגל.',
  ),
  e(
    'warm-dyn-1-arm-circle',
    'סיבובי זרועות',
    'Arm Circles',
    'dynamic_stretch',
    1,
    'ytw',
    'פשקו זרועות לצדדים בגובה הכתפיים ובצעו סיבובים קטנים המתרחבים בהדרגה קדימה, ולאחר מכן החליפו כיוון לאחורה.',
  ),
  e(
    'warm-dyn-1-torso-twist',
    'סיבובי גו קלים',
    'Torso Twists',
    'dynamic_stretch',
    1,
    'twist',
    'עמדו ברוחב הכתפיים עם ידיים משוחררות, וסובבו את פלג הגוף העליון מצד לצד בתנועה נינוחה תוך שמירה על אגן יציב.',
  ),
  e(
    'warm-dyn-2-walking-lunge',
    'לאנג׳ הליכה עם סיבוב',
    'Walking Lunge with Twist',
    'dynamic_stretch',
    2,
    'lunge',
    'צעדו למכרע קדימה וסובבו את פלג הגוף לכיוון הרגל הקדמית. דחפו לעמידה והמשיכו לצעד הבא ברגל השנייה.',
  ),
  e(
    'warm-dyn-2-hip-circle',
    'סיבובי ירך בעמידה',
    'Hip Circles',
    'dynamic_stretch',
    2,
    'twist',
    'הניחו ידיים על המותניים ובצעו סיבובים רחבים של האגן בכיוון אחד, ולאחר מכן בכיוון הנגדי.',
  ),
  e(
    'warm-dyn-2-cat-cow',
    'חתול-פרה בעמידה על ארבע',
    'Cat-Cow',
    'dynamic_stretch',
    2,
    'cobra',
    'עמדו על ארבע. בשאיפה הבליטו את הבטן והרימו את הראש, ובנשיפה עגלו את הגב והורידו את הראש פנימה.',
  ),
  e(
    'warm-dyn-3-inchworm',
    'אינצ׳וורם עד פלאנק',
    'Inchworm to Plank',
    'dynamic_stretch',
    3,
    'plank',
    'מעמידה, כופפו קדימה והניחו ידיים על הרצפה. "צעדו" בידיים קדימה עד תנוחת פלאנק, ואז חזרה לרגליים.',
  ),
  e(
    'warm-dyn-3-world-greatest',
    'המתיחה הטובה בעולם',
    "World's Greatest Stretch",
    'dynamic_stretch',
    3,
    'lunge',
    'היכנסו למכרע עמוק, הניחו יד אחת על הרצפה וסובבו את פלג הגוף כלפי מעלה כשהיד השנייה מושטת לתקרה.',
  ),
  e(
    'warm-dyn-1-dynamic-chest-stretch',
    'מתיחת חזה דינמית',
    'Dynamic Chest Stretch',
    'dynamic_stretch',
    1,
    'ytw',
    'הרימו ידיים לזווית של 90 מעלות מהצדדים ומשכו את המרפקים לאחור בפעימות קצרות וקצביות לפתיחת החזה.',
  ),
  e(
    'warm-dyn-2-chest-tap-pushup',
    'שכיבת סמיכה עם טפיחת חזה',
    'Chest Tap Push-Up',
    'dynamic_stretch',
    2,
    'pushup',
    'בצעו שכיבת סמיכה בקצב נינוח, ובעלייה טפחו בקלות על החזה לפני החזרה למטה.',
  ),
  e(
    'warm-dyn-1-standing-lateral-stretch',
    'מתיחת צד בעמידה',
    'Standing Lateral Stretch',
    'dynamic_stretch',
    1,
    'twist',
    'הרימו זרוע אחת מעל הראש והטו את הגו לצד השני בתנועה נינוחה, וחזרו למרכז. החליפו צד.',
  ),
  e(
    'warm-dyn-2-plank-twist',
    'פלאנק עם סיבוב',
    'Front Plank With Twist',
    'dynamic_stretch',
    2,
    'twist',
    'מתנוחת פלאנק גבוה, סובבו את האגן וכתף אחת לכיוון הרצפה מצד אחד, וחזרו למרכז לפני החלפת צד.',
  ),
  e(
    'warm-dyn-3-hanging-twist-raise',
    'הרמת רגליים בתלייה עם סיבוב',
    'Hanging Straight Twisting Leg Hip Raise',
    'dynamic_stretch',
    3,
    'ytw',
    'היתלו על מוט מתח בזרועות ישרות והרימו את הרגליים תוך סיבוב קל של האגן לצד אחד ואז לצד השני.',
  ),
  e(
    'warm-dyn-2-squat-overhead-twist',
    'סקוואט עם הושטה וסיבוב',
    'Squat To Overhead Reach With Twist',
    'dynamic_stretch',
    2,
    'squat',
    'רדו לסקוואט, ובעלייה הושטו ידיים מעל הראש תוך סיבוב קל של הגו לצד אחד.',
  ),
  e(
    'warm-dyn-2-crab-twist-toe-touch',
    'תנוחת סרטן עם נגיעה בבוהן',
    'Crab Twist Toe Touch',
    'dynamic_stretch',
    2,
    'twist',
    'שבו בתנוחת סרטן עם כפות ידיים ורגליים תומכות מהרצפה כלפי מעלה. הרימו יד אחת וגעו בבוהן הרגל הנגדית.',
  ),
  e(
    'warm-dyn-1-back-forth-step',
    'צעד קדימה ואחורה',
    'Back And Forth Step',
    'dynamic_stretch',
    1,
    'stepup',
    'צעדו קדימה ואחורה בקצב נינוח תוך נפנוף חופשי של הידיים לשחרור הכתפיים והגב העליון.',
  ),
  e(
    'warm-dyn-1-ankle-circle',
    'סיבובי קרסול',
    'Ankle Circles',
    'dynamic_stretch',
    1,
    'calf',
    'עמדו על רגל אחת ובצעו סיבובים איטיים ורחבים עם קרסול הרגל השנייה, ואז החליפו כיוון וכן רגל.',
  ),
  e(
    'warm-dyn-1-squat-overhead-reach',
    'סקוואט עם הושטה מעל הראש',
    'Squat To Overhead Reach',
    'dynamic_stretch',
    1,
    'squat',
    'רדו לסקוואט נינוח, ובעלייה הושטו את הידיים ישר מעל הראש.',
  ),
  e(
    'warm-dyn-2-posterior-step-reach',
    'מכרע אחורי עם הושטה',
    'Posterior Step To Overhead Reach',
    'dynamic_stretch',
    2,
    'lunge',
    'קחו צעד אחורי למכרע והרימו את הידיים ישר מעל הראש למתיחת הירך הקדמית.',
  ),
  e(
    'warm-dyn-1-half-knee-bend',
    'חצאי כפיפות ברכיים',
    'Half Knee Bends',
    'dynamic_stretch',
    1,
    'squat',
    'בצעו כפיפות ברכיים קטנות ומהירות בטווח תנועה חלקי כדי להעלות זרימת דם לרגליים.',
  ),
  e(
    'warm-dyn-2-runners-stretch',
    'מתיחת אצנים',
    'Runners Stretch',
    'dynamic_stretch',
    2,
    'lunge',
    'עברו לסירוגין בין שכיבת סמיכה למכרע עמוק קדימה, לפתיחת מפרקי הירך והירך האחורית.',
  ),
  e(
    'warm-dyn-1-side-bend',
    'כפיפת צד 45 מעלות',
    '45° Side Bend',
    'dynamic_stretch',
    1,
    'twist',
    'עמדו זקוף והתכופפו הצידה בזווית מתונה, לסירוגין ימין ושמאל, לחימום שרירי הצד.',
  ),
  e(
    'warm-dyn-2-russian-twist',
    'סיבוב רוסי',
    'Russian Twist',
    'dynamic_stretch',
    2,
    'twist',
    'שבו עם רגליים מורמות מעט מהרצפה וסובבו את פלג הגוף העליון מצד לצד.',
  ),
  e(
    'warm-dyn-2-hip-lift-twist',
    'הרמת אגן עם סיבוב',
    'Twist Hip Lift',
    'dynamic_stretch',
    2,
    'bridge',
    'שכבו על הגב והרימו את האגן מהרצפה תוך סיבוב קל הצידה, וחזרו למטה.',
  ),
  e(
    'warm-dyn-2-isometric-wipers',
    'מגבים איזומטריים',
    'Isometric Wipers',
    'dynamic_stretch',
    2,
    'legraise',
    'שכבו על הגב עם רגליים ישרות מורמות, והניעו אותן לאט ימינה ושמאלה כמו מגבי רכב.',
  ),

  /* ------------------------------------------------ העלאת דופק */
  e(
    'warm-pulse-1-march',
    'צעידה קלה במקום',
    'Easy Marching',
    'pulse_raiser',
    1,
    'highknee',
    'צעדו במקום בקצב נינוח תוך הרמת ברכיים מתונה, כדי להתחיל להעלות את הדופק בהדרגה.',
  ),
  e(
    'warm-pulse-1-arm-swing',
    'נפנוף ידיים בהליכה קלה',
    'Arm Swings while Marching',
    'pulse_raiser',
    1,
    'ytw',
    'המשיכו לצעוד במקום תוך נפנוף חופשי וקצבי של הידיים קדימה ואחורה.',
  ),
  e(
    'warm-pulse-2-jumping-jack',
    'ג׳אמפינג ג׳ק קל',
    'Easy Jumping Jacks',
    'pulse_raiser',
    2,
    'jumpingjack',
    'בצעו ג׳אמפינג ג׳ק בקצב מתון: פשקו רגליים וידיים בקפיצה קלה, וחזרו למרכז.',
  ),
  e(
    'warm-pulse-2-high-knees',
    'ברכיים גבוהות בקצב בינוני',
    'High Knees',
    'pulse_raiser',
    2,
    'highknee',
    'רוצו במקום תוך הרמת הברכיים לגובה הירך בקצב בינוני.',
  ),
  e(
    'warm-pulse-3-skater',
    'קפיצות סקייטר קלות',
    'Light Skater Hops',
    'pulse_raiser',
    3,
    'skater',
    'קפצו לצדדים מרגל לרגל בתנועת סקייטר קלה, תוך שמירה על נחיתה רכה.',
  ),
].map(withRealGif);
